export const SCENE_IDS = {
  POSITION_DETAIL_SCENE: "POSITION_DETAIL_SCENE",
  POOL_DETAIL_SCENE: "POOL_DETAIL_SCENE",
  CREATE_POSITION_SCENE: "CREATE_POSITION_SCENE",
  // need refactor
  TOKEN_INPUT: "TOKEN_INPUT_SCENE",
  POOL_SELECTION: "POOL_SELECTION_SCENE",
  STRATEGY_SELECTION: "STRATEGY_SELECTION_SCENE",
  AMOUNT_INPUT: "AMOUNT_INPUT_SCENE",
  CUSTOM_AMOUNT: "CUSTOM_AMOUNT_SCENE",
  SIDE_SELECTION: "SIDE_SELECTION_SCENE",
  CONFIRMATION: "CONFIRMATION_SCENE",
  POSITION_PREVIEW: "POSITION_PREVIEW_SCENE",

  HELP_SCENE: "HELP_SCENE",
};
